# -*- coding: utf-8 -*-
"""B21BB007.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DHDUnW8-VptXUKVPk2tbaYP7RfNyt5P9

**Question 1**
"""

import pandas as pd
data = pd.read_csv("Superstore.csv" , encoding= "windows-1252")



data_numerical_features = data.select_dtypes(include='number')
print(data_numerical_features)
data_categorical_features = data.select_dtypes(include='category')
print(data_categorical_features)

import pandas as pd
data.describe()

data.info()

"""**Question 2**"""

import numpy as np

a =np.random.uniform(0 , 2 , 2)
print(a)

print(np.average(a))

print(np.std(a))
print(np.mean(a))

array = np.random.randint(10, size=(3, 3))
print(array)

w, v = np.linalg.eig(array)
print(w)
print(v)
print(np.linalg.inv(array))
print (np.linalg.det(array))